# Make File
PROGNAME=eap
RSI_SDK_PATH = ../../../../

# Includes
CFLAGS += 
# Defines
CFLAGS += 
# Sources
APPLICATION_SOURCES = rsi_eap_connectivity.c 

# SDK features
SDK_FEATURES = wlan sockets certificates 

include $(RSI_SDK_PATH)/sapi/sapi.mk
